insert into Song (id, title, artist, genre) values (1, 'Oak, The (Balanta)', 'Leonie Breinlein', 'Comedy|Drama');
insert into Song (id, title, artist, genre) values (2, 'Commare secca, La (Grim Reaper, The)', 'Frasquito Anney', 'Drama|Mystery');
insert into Song (id, title, artist, genre) values (3, 'Tequila Sunrise', 'Julianna Buscombe', 'Action|Drama|Romance|Thriller');
insert into Song (id, title, artist, genre) values (4, 'Cycling with Moliere (Alceste à bicyclette)', 'Lief Lingley', 'Comedy|Drama');
insert into Song (id, title, artist, genre) values (5, 'Hollow Man', 'Rosana Aizikovich', 'Horror|Sci-Fi|Thriller');
insert into Song (id, title, artist, genre) values (6, 'Special Day, A (Giornata particolare, Una)', 'Shea Dalrymple', 'Drama|War');
insert into Song (id, title, artist, genre) values (7, '2046', 'Marylynne Ordish', 'Drama|Fantasy|Romance|Sci-Fi');
insert into Song (id, title, artist, genre) values (8, 'Liar''s Dice', 'Joyan McGifford', 'Adventure|Children|Drama');
insert into Song (id, title, artist, genre) values (9, 'Killer Joe', 'Olwen Coppo', 'Crime|Thriller');
insert into Song (id, title, artist, genre) values (10, 'Town Without Pity', 'Kristan Pagel', 'Drama');
insert into Song (id, title, artist, genre) values (11, 'Chained for Life', 'Florian Bartrop', 'Crime');
insert into Song (id, title, artist, genre) values (12, 'Romance & Cigarettes', 'Robenia Baldack', 'Comedy|Drama|Musical|Romance');
insert into Song (id, title, artist, genre) values (13, 'Special Delivery', 'Jessa Zorro', '(no genres listed)');
insert into Song (id, title, artist, genre) values (14, 'White Massai, The (Weisse Massai, Die)', 'Margery Dorken', 'Drama|Romance');
insert into Song (id, title, artist, genre) values (15, 'High Fidelity', 'Reggi Nestle', 'Comedy|Drama|Romance');
insert into Song (id, title, artist, genre) values (16, 'Keeper of the Flame', 'Rutger Staten', 'Drama|Mystery');
insert into Song (id, title, artist, genre) values (17, 'I Belong (Som du ser meg)', 'Orella Boutton', 'Drama');
insert into Song (id, title, artist, genre) values (18, 'Great!', 'Justen Erwin', 'Comedy');
insert into Song (id, title, artist, genre) values (19, 'Fear Over the City', 'Eunice Featherston', 'Action|Crime|Drama');
insert into Song (id, title, artist, genre) values (20, 'Dupes, The (Al-makhdu''un)', 'Arny Nowakowska', 'Drama');